/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GerenciadorTarefas;

import GerenciadorTarefas.controller.controller;
import GerenciadorTarefas.dao.tarefasDao;
import GerenciadorTarefas.dao.usuarioDao;
import GerenciadorTarefas.model.Tarefas;
import GerenciadorTarefas.model.Usuario;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       
    }
}
