/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhoRpg;

import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author PEDROHENRIQUEEICHAMA
 */
public class TelaSecundaria extends javax.swing.JFrame {
    private String nomeUser;
    private String classeUser;
    
    /**
     * Creates new form TelaSecundaria
     */
    
    public TelaSecundaria(String nome, String classe){
        initComponents();
        setLocationRelativeTo(null);
        this.nomeUser = nome;
        this.classeUser = classe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        entrarBtn = new javax.swing.JButton();
        forcaLabek = new javax.swing.JLabel();
        manaLabel = new javax.swing.JLabel();
        agilidade = new javax.swing.JLabel();
        vidaLabel = new javax.swing.JLabel();
        dadoBtn = new javax.swing.JButton();
        vida = new javax.swing.JLabel();
        forca = new javax.swing.JLabel();
        mana = new javax.swing.JLabel();
        AgilidadeLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(26, 16, 53));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 161, 29));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATRIBUTOS");

        entrarBtn.setBackground(new java.awt.Color(26, 16, 53));
        entrarBtn.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        entrarBtn.setForeground(new java.awt.Color(241, 161, 29));
        entrarBtn.setText("Proximo");
        entrarBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 161, 29), 3));
        entrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarBtnActionPerformed(evt);
            }
        });

        forcaLabek.setBackground(new java.awt.Color(255, 255, 255));
        forcaLabek.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        forcaLabek.setForeground(new java.awt.Color(241, 161, 29));
        forcaLabek.setText("Força:");

        manaLabel.setBackground(new java.awt.Color(255, 255, 255));
        manaLabel.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        manaLabel.setForeground(new java.awt.Color(241, 161, 29));
        manaLabel.setText("Mana:");

        agilidade.setBackground(new java.awt.Color(255, 255, 255));
        agilidade.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        agilidade.setForeground(new java.awt.Color(241, 161, 29));

        vidaLabel.setBackground(new java.awt.Color(255, 255, 255));
        vidaLabel.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        vidaLabel.setForeground(new java.awt.Color(241, 161, 29));
        vidaLabel.setText("Vida:");

        dadoBtn.setBackground(new java.awt.Color(26, 16, 53));
        dadoBtn.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        dadoBtn.setForeground(new java.awt.Color(241, 161, 29));
        dadoBtn.setText("Rolar Dado");
        dadoBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 161, 29), 3));
        dadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadoBtnActionPerformed(evt);
            }
        });

        vida.setBackground(new java.awt.Color(255, 255, 255));
        vida.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        vida.setForeground(new java.awt.Color(241, 161, 29));

        forca.setBackground(new java.awt.Color(255, 255, 255));
        forca.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        forca.setForeground(new java.awt.Color(241, 161, 29));

        mana.setBackground(new java.awt.Color(255, 255, 255));
        mana.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        mana.setForeground(new java.awt.Color(241, 161, 29));

        AgilidadeLabel.setBackground(new java.awt.Color(255, 255, 255));
        AgilidadeLabel.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        AgilidadeLabel.setForeground(new java.awt.Color(241, 161, 29));
        AgilidadeLabel.setText("Agilidade:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(entrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(vidaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(vida, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dadoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(manaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                        .addComponent(forcaLabek, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(AgilidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(agilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(forca, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(mana, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(190, 190, 190))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forcaLabek, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vida, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mana, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgilidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(dadoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(entrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBtnActionPerformed
    new TelaJogo().setVisible(true);
    this.dispose();

    }//GEN-LAST:event_entrarBtnActionPerformed

    private void dadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadoBtnActionPerformed
        criarPersonagem();
               
    }//GEN-LAST:event_dadoBtnActionPerformed

   
    private void criarPersonagem(){
        Personagem personagem = new Personagem(nomeUser, 0 ,0 ,0 , 0);
        if(classeUser == "Arqueiro"){
        personagem.vida = personagem.rolarDados(3, 6);
        personagem.mana = personagem.rolarDados(3,6);
        personagem.forca = personagem.rolarDados(3,6);
        personagem.agilidade = personagem.rolarDados(3,6)+3;
        }else if(classeUser == "Bárbaro"){
        personagem.vida = personagem.rolarDados(3, 6);
        personagem.mana = personagem.rolarDados(3,6);
        personagem.forca = personagem.rolarDados(3,6)+2;
        personagem.agilidade = personagem.rolarDados(3,6);
        }else if(classeUser == "Ladino"){
        personagem.vida = personagem.rolarDados(3, 6);
        personagem.mana = personagem.rolarDados(3,6);
        personagem.forca = personagem.rolarDados(3,6);
        personagem.agilidade = personagem.rolarDados(3,6)+4;
        }else if(classeUser == "Mago"){
        personagem.vida = personagem.rolarDados(3, 6);
        personagem.mana = personagem.rolarDados(3,6)+3;
        personagem.forca = personagem.rolarDados(3,6);
        personagem.agilidade = personagem.rolarDados(3,6);
        }
        forca.setText(Integer.toString(personagem.forca));
        vida.setText(Integer.toString(personagem.vida));
        mana.setText(Integer.toString(personagem.mana));
        agilidade.setText(Integer.toString(personagem.agilidade));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSecundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgilidadeLabel;
    private javax.swing.JLabel agilidade;
    private javax.swing.JButton dadoBtn;
    private javax.swing.JButton entrarBtn;
    private javax.swing.JLabel forca;
    private javax.swing.JLabel forcaLabek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mana;
    private javax.swing.JLabel manaLabel;
    private javax.swing.JLabel vida;
    private javax.swing.JLabel vidaLabel;
    // End of variables declaration//GEN-END:variables
}
