/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package revisao;

import java.sql.Connection;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       // ConexaoSQLite minhaConexao = new ConexaoSQLite();
       // minhaConexao.conectar();
       
       Connection conexao = ConexaoSQLite.conectar();
       
       //CriarTabela.criarTabelaUsuarios(conexao);
       
       //InserirUsuarios.inserirUsuario(conexao, "Pedro", "Pedro@Gmail.com");
       //InserirUsuarios.inserirUsuario(conexao, "Diego", "diego@Gmail.com");
       //InserirUsuarios.inserirUsuario(conexao, "Erik", "erik@Gmail.com");
       
       // ListarUsuarios.ListarUsuarios(conexao);
       //AtualizarUsuario.atualizarUusario(conexao, 1, "lucas@gmail.com", "", "Lucas");
       
       // DeletarUsuario.deletarUsuario(conexao, "erik@Gmail.com");
       
    }
}
