/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sextou;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author PEDROHENRIQUEEICHAMA
 */
public class formulario extends javax.swing.JFrame {

    /**
     * Creates new form formulario
     */
    public formulario() {
        initComponents();
        stateList.addItem("SP");
        stateList.addItem("RS");
        stateList.addItem("RJ");
        
        // Inicia o programa com o 'no1' selecionado
        no1.setSelected(true);
        
        no2.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        nameFIld = new javax.swing.JTextField();
        stateList = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        programminLanguages = new javax.swing.JLabel();
        checkjs = new javax.swing.JCheckBox();
        checkts = new javax.swing.JCheckBox();
        checkpy = new javax.swing.JCheckBox();
        checkjava = new javax.swing.JCheckBox();
        checkphp = new javax.swing.JCheckBox();
        yes1 = new javax.swing.JRadioButton();
        no1 = new javax.swing.JRadioButton();
        programminLanguages1 = new javax.swing.JLabel();
        programminLanguages2 = new javax.swing.JLabel();
        yes2 = new javax.swing.JRadioButton();
        no2 = new javax.swing.JRadioButton();
        sometimes = new javax.swing.JRadioButton();

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox5.setText("jCheckBox1");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("TS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        nameFIld.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameFIld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameFIld.setText("Name:");
        nameFIld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFIldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFIldFocusLost(evt);
            }
        });
        nameFIld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFIldActionPerformed(evt);
            }
        });

        stateList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateListActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("State");

        btnRegister.setBackground(new java.awt.Color(51, 102, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        programminLanguages.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        programminLanguages.setForeground(new java.awt.Color(255, 255, 255));
        programminLanguages.setText("Programmin languages");

        checkjs.setBackground(new java.awt.Color(0, 0, 0));
        checkjs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkjs.setForeground(new java.awt.Color(255, 255, 255));
        checkjs.setText("JS");

        checkts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkts.setForeground(new java.awt.Color(255, 255, 255));
        checkts.setText("TS");

        checkpy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkpy.setForeground(new java.awt.Color(255, 255, 255));
        checkpy.setText("PY");

        checkjava.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkjava.setForeground(new java.awt.Color(255, 255, 255));
        checkjava.setText("JAVA");

        checkphp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkphp.setForeground(new java.awt.Color(255, 255, 255));
        checkphp.setText("PHP");

        buttonGroup1.add(yes1);
        yes1.setForeground(new java.awt.Color(255, 255, 255));
        yes1.setText("Yes");

        buttonGroup1.add(no1);
        no1.setForeground(new java.awt.Color(255, 255, 255));
        no1.setText("No");

        programminLanguages1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        programminLanguages1.setForeground(new java.awt.Color(255, 255, 255));
        programminLanguages1.setText("Do you use programming on your job?");

        programminLanguages2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        programminLanguages2.setForeground(new java.awt.Color(255, 255, 255));
        programminLanguages2.setText("Are you student?");

        buttonGroup2.add(yes2);
        yes2.setForeground(new java.awt.Color(255, 255, 255));
        yes2.setText("Yes");

        buttonGroup2.add(no2);
        no2.setForeground(new java.awt.Color(255, 255, 255));
        no2.setText("No");

        buttonGroup2.add(sometimes);
        sometimes.setForeground(new java.awt.Color(255, 255, 255));
        sometimes.setText("Sometimes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stateList, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameFIld, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(yes2)
                                    .addGap(65, 65, 65)
                                    .addComponent(no2)
                                    .addGap(54, 54, 54)
                                    .addComponent(sometimes))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(programminLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(checkjs)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(checkts)
                                                            .addGap(78, 78, 78)
                                                            .addComponent(checkpy))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                            .addComponent(yes1)
                                                            .addGap(74, 74, 74)
                                                            .addComponent(no1)
                                                            .addGap(0, 0, Short.MAX_VALUE)))
                                                    .addGap(13, 13, 13))
                                                .addComponent(programminLanguages2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(89, 89, 89)
                                            .addComponent(checkjava))
                                        .addComponent(programminLanguages1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(42, 42, 42)
                                    .addComponent(checkphp))))
                        .addGap(0, 176, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(nameFIld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateList, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(programminLanguages)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkjs)
                    .addComponent(checkts)
                    .addComponent(checkpy)
                    .addComponent(checkjava)
                    .addComponent(checkphp))
                .addGap(37, 37, 37)
                .addComponent(programminLanguages2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yes1)
                    .addComponent(no1))
                .addGap(46, 46, 46)
                .addComponent(programminLanguages1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yes2)
                            .addComponent(no2)
                            .addComponent(sometimes))))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFIldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFIldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFIldActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        /*// 1 - Lê o nome registrado
        String name = nameFIld.getText();
        // 2 - Verifica o estado selecionado
        String state = stateList.getSelectedItem().toString();                                                                                        
        // 3 - Abre uma janela informando os dados
        if(state == "RS"){
            JOptionPane.showMessageDialog(this, name + ", you are gaucho! ");
        }else if(state == "RJ"){
            JOptionPane.showMessageDialog(this, name + ", you are carioca! ");
        }else if(state == "SP"){
            JOptionPane.showMessageDialog(this, name + ", you are gay! ");
        }
        */
        
        showProgrammingLanguages();
        student();
        programmingJob();
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void nameFIldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFIldFocusGained
        if("Name:".equals(nameFIld.getText())){
            nameFIld.setText("");
        }
    }//GEN-LAST:event_nameFIldFocusGained

    private void nameFIldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFIldFocusLost
        if("".equals(nameFIld.getText())){
            nameFIld.setText("Name:");
        }
    }//GEN-LAST:event_nameFIldFocusLost

    private void stateListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateListActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void showProgrammingLanguages(){
        // Verifica se o checkjs está selecionado
        boolean jsSelected = checkjs.isSelected();       
        // Verifca se o checkts esta selecionado
        boolean tsSelected = checkts.isSelected();
        // Verifica se o checkpy esta selecionado
        boolean pySelected = checkpy.isSelected();  
        boolean javaSelected = checkjava.isSelected();
        // Verifiva se o checkphp esta selecionado
        boolean phpSelected = checkphp.isSelected();
        
        
        String message = "You know thesse languages: ";
        
        // Se o checkjs estiver selecionado, concatena a palavra Javascrip na mensagem
        /*if(jsSelected){message += "\n - Javascript";}
        if(tsSelected){message += "\n - Typescript";}
        if(pySelected){message += "\n - Python";}
        if(javaSelected){message += "\n - Java";}
        if(phpSelected){message += "\n - PHP";}
        JOptionPane.showMessageDialog(this, message);
        */
        
        
        // Array que contem todos os CheckBoxes
        JCheckBox[] checks =  {checkjs, checkts, checkpy, checkjava, checkpy, checkphp};
        // Array que contem as strings
        String[] languages = {"Javascript", "Typescript", "Python", "Java", "PHP"};
        
        for(int i = 0; i < checks.length; i++){
            // Verifica se o checkList foi selecionado
            if(checks[i].isSelected()){
                message += "\n" + languages[i];
                JOptionPane.showMessageDialog(this, message);
            }
        }
        
    }
    
    private void student(){
        // verifica se o botão de yes foi clicado
        boolean isStudent = yes1.isSelected();
        
        
        if(isStudent){
            System.out.println("You are a student! ");
        }else{
            System.out.println("You are not a student! ");
        }
        
        
    }
    
    private void programmingJob(){
        boolean useProgramming = yes2.isSelected();
        boolean notuseProgramming = no2.isSelected();
        boolean sometimesusePrograming = sometimes.isSelected();
        
        if(useProgramming){
            System.out.println("You use programming on your job! ");
        }else if(notuseProgramming){
            System.out.println("You not use programming on your job! ");
        }else {
            System.out.println("Sometimes you use programmin on your job! ");
        }
            
            
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox checkjava;
    private javax.swing.JCheckBox checkjs;
    private javax.swing.JCheckBox checkphp;
    private javax.swing.JCheckBox checkpy;
    private javax.swing.JCheckBox checkts;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameFIld;
    private javax.swing.JRadioButton no1;
    private javax.swing.JRadioButton no2;
    private javax.swing.JLabel programminLanguages;
    private javax.swing.JLabel programminLanguages1;
    private javax.swing.JLabel programminLanguages2;
    private javax.swing.JRadioButton sometimes;
    private javax.swing.JComboBox<String> stateList;
    private javax.swing.JRadioButton yes1;
    private javax.swing.JRadioButton yes2;
    // End of variables declaration//GEN-END:variables
}
