/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sextou;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PEDROHENRIQUEEICHAMA
 */
public class TelaComTabela extends javax.swing.JFrame {
    
    // Define o modelo da tabela (ou seja, de onde ela lê os dados)
    DefaultTableModel modelo;
    
    /**
     * Creates new form TelaComTabela
     */
    public TelaComTabela() {
        initComponents();
        modelo = new DefaultTableModel();
        // 'addColumn' adiciona uma coluna ao modelo
        modelo.addColumn("Nome");
        modelo.addColumn("idade");
        modelo.addColumn("Altura");
        // Informa que minha tabela vai agora ler os dados do modelo que criei
        userTable.setModel(modelo);
        
        // 'addRow' adiciona uma linha ao modelo
        modelo.addRow(new Object[]{"Pedro", 16, 1.77});
        modelo.addRow(new Object[]{"Diego", 15, 1.68});
        modelo.addRow(new Object[]{"Bernardo", 18, 1.75});
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        nameFild = new javax.swing.JTextField();
        ageFild = new javax.swing.JTextField();
        heigthFild = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        selectLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tabela Usuarios");

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        nameFild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameFild.setText("Digite seu nome:");
        nameFild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFildFocusLost(evt);
            }
        });

        ageFild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ageFild.setText("Digite sua idade:");
        ageFild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFildFocusLost(evt);
            }
        });

        heigthFild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        heigthFild.setText("Digite sua altura:");
        heigthFild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                heigthFildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                heigthFildFocusLost(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(0, 204, 255));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(0, 0, 0));
        saveBtn.setText("Salvar");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        removeBtn.setBackground(new java.awt.Color(255, 51, 51));
        removeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(0, 0, 0));
        removeBtn.setText("Remover");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        selectLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selectLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectLabel.setText("Valor Selecionado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(removeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(nameFild)
                            .addComponent(ageFild)
                            .addComponent(heigthFild)
                            .addComponent(selectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(nameFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ageFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(heigthFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(selectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        insertROw();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void nameFildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFildFocusGained
        if("Digite seu nome:".equals(nameFild.getText())){
        nameFild.setText("");
    }
    }//GEN-LAST:event_nameFildFocusGained

    private void nameFildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFildFocusLost
        if("".equals(nameFild.getText())){
            nameFild.setText("Digite seu nome:");
        }
    }//GEN-LAST:event_nameFildFocusLost

    private void ageFildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFildFocusGained
        if("Digite sua idade:".equals(ageFild.getText())){
            ageFild.setText("");
        }
            
    }//GEN-LAST:event_ageFildFocusGained

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        removeRow();
    }//GEN-LAST:event_removeBtnActionPerformed

    private void ageFildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFildFocusLost
        if("".equals(ageFild.getText())){
            ageFild.setText("Digite sua idade:");
        }
    }//GEN-LAST:event_ageFildFocusLost

    private void heigthFildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heigthFildFocusGained
        if("Digite sua altura:".equals(heigthFild.getText())){
            heigthFild.setText("");
        }
    }//GEN-LAST:event_heigthFildFocusGained

    private void heigthFildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_heigthFildFocusLost
        if("".equals(heigthFild.getText())){
            heigthFild.setText("Digite sua altura:");
        }
    }//GEN-LAST:event_heigthFildFocusLost

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        getValue();
    }//GEN-LAST:event_userTableMouseClicked

    
    private void insertROw(){
        // Armanezar o valores dos campos de texto (textFild)
        String name = nameFild.getText();
        int age = Integer.parseInt(ageFild.getText());
        double heigth = Double.parseDouble(heigthFild.getText());
        
        // Adicionar os valores no Array
        Object[] array = {name, age, heigth};
        
        // Adicionar a linha, passando o array com os dados
        modelo.addRow(array);
    }
    
    private void removeRow(){
        // 'getSelectRow' armazena o numero que a representa a linha seleciona
        int row = userTable.getSelectedRow();
        
        // Para remover, primerio garantimos que selcionamos algo
        if(row != -1){
            modelo.removeRow(row);
        }else {
            JOptionPane.showMessageDialog(this, "Para deletar, você precisa selecionar uma linha! ");
        }
       
        
            
    }
    
    private void getValue(){
            int row = userTable.getSelectedRow();
            int column = userTable.getSelectedColumn();
            
            // Pega o valor da célula (cada quadradinho da tabela se chama celula)
            String cell = modelo.getValueAt(row, column).toString();
            
            selectLabel.setText("Valor selecionado: " + cell);
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaComTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaComTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaComTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaComTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaComTabela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageFild;
    private javax.swing.JTextField heigthFild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameFild;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel selectLabel;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
