/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tratamentoDeExcessoes;

public class App {
    
     
    public static void main(String[] args) {
        double resultado = Divisao.dividir(1,1);
        System.out.println(resultado);
        int[] numeros = {10,5,90}; // 0,1,2
        System.out.println(numeros[3]);
        
        // dentro do bloco try, colocamos o codigo que queremos executar
        // mas que pode gerar um erro(excessão)
        try{
            System.out.println(numeros[3]);
            
        }
        // catch significa capture
        // ele captura o erro e podemos mostrar a mensagem de forma clara
        catch(Exception erro){
            System.out.println("Erro: " + erro.getMessage());
        }
    }
    
}
