/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoLogin;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author PEDROHENRIQUEEICHAMA
 */
public class TelaPerfil extends javax.swing.JFrame {

    private String emailUser;
    private String nomeUser;

    /**
     * Creates new form TelaPerfil
     */
    public TelaPerfil() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public TelaPerfil(String email, String nome) {
        initComponents();
        this.emailUser = email;
        emailFild.setText(this.emailUser);
        this.nomeUser = nome;
        nameFild.setText(this.nomeUser);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailFild = new javax.swing.JTextField();
        voltarBtn = new javax.swing.JButton();
        alterarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameFild = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        deletarBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emailFild.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailFild.setForeground(new java.awt.Color(0, 0, 0));
        emailFild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFildFocusLost(evt);
            }
        });
        emailFild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFildActionPerformed(evt);
            }
        });

        voltarBtn.setBackground(new java.awt.Color(102, 102, 102));
        voltarBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltarBtn.setForeground(new java.awt.Color(255, 255, 255));
        voltarBtn.setText("Sair");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        alterarBtn.setBackground(new java.awt.Color(0, 204, 102));
        alterarBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alterarBtn.setForeground(new java.awt.Color(255, 255, 255));
        alterarBtn.setText("Alterar");
        alterarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Perfil");

        nameFild.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameFild.setForeground(new java.awt.Color(0, 0, 0));
        nameFild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFildFocusLost(evt);
            }
        });

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        deletarBtn.setBackground(new java.awt.Color(255, 51, 51));
        deletarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletarBtn.setText("Deletar Conta");
        deletarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1)
                            .addComponent(emailFild)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(286, 286, 286)
                                .addComponent(alterarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameFild)
                            .addComponent(deletarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nameFild, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailFild, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alterarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(deletarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFildFocusGained
        if ("Digite seu email:".equals(emailFild.getText())) {
            emailFild.setText("");
        }
    }//GEN-LAST:event_emailFildFocusGained

    private void emailFildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFildFocusLost
        if ("".equals(emailFild.getText())) {
            emailFild.setText("Digite seu email:");
        }
    }//GEN-LAST:event_emailFildFocusLost

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarBtnActionPerformed

    private void nameFildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFildFocusGained
        if ("Digite seu nome:".equals(nameFild.getText())) {
            nameFild.setText("");
        }
    }//GEN-LAST:event_nameFildFocusGained

    private void nameFildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFildFocusLost
        if ("".equals(nameFild.getText())) {
            nameFild.setText("Digite seu nome:");
        }
    }//GEN-LAST:event_nameFildFocusLost

    private void emailFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFildActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void deletarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBtnActionPerformed

        // Exibe um dialago de confirmação
        int resposta = JOptionPane.showConfirmDialog(this,
                "Confirma a exclusão do usuario? ",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION);// Tipo de opções

        String email = emailFild.getText();

        if (resposta == JOptionPane.YES_NO_OPTION) {
            Banco.deletarUsuario(email);
            new TelaLogin().setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(this, "Usuario deletado com sucesso! ");
        } else {

        }


    }//GEN-LAST:event_deletarBtnActionPerformed

    private void alterarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarBtnActionPerformed
        String novoNome = nameFild.getText();
        String novoEmail = emailFild.getText();
        char[] novaSenha = jPasswordField1.getPassword();
        if (novoNome.trim().equals("") || novoEmail.trim().equals("") || Arrays.equals(novaSenha, new char[]{})) {
            JOptionPane.showMessageDialog(this, "Não");
        } else {
            if (Banco.atualizarUsuario(emailUser, novoNome, novoEmail, novaSenha)) {
                emailUser = novoEmail;
                JOptionPane.showMessageDialog(this, "Atualização concluida. ");
            }
        }


    }//GEN-LAST:event_alterarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarBtn;
    private javax.swing.JToggleButton deletarBtn;
    private javax.swing.JTextField emailFild;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField nameFild;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
