/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package login.bcrypt.mcv;

import login.bcrypt.mcv.dao.usuarioDao;
import login.bcrypt.mcv.model.Usuario;
import login.bcrypt.mcv.service.usuarioService;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //Usuario usuario = usuarioDao.buscarEmail("pedro@gmail.com");
        //System.out.println(usuario.getSenha());
        
        
    }
}
