/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GerenciadorBiblioteca;

import GerenciadorBiblioteca.dao.LivroDAO;
import GerenciadorBiblioteca.model.Livro;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Livro livro1 = new Livro( "Harry Potter", "J.K Rowling", 1997, "Fantasia");
        //LivroDAO.cadastrar(livro1);
        /*System.out.println("ID | " + "Titulo | " + "Autor | " + "Ano de publicação | " + "Categoria");
        ArrayList<Livro> livros = LivroDAO.listar();
        for(Livro livro : livros){
            
            System.out.println(livro.getId() + " | " + livro.getTitulo() + " | "  + livro.getAutor() + " | "  + livro.getAnoPublicacao()+ " | "  + livro.getCategoria());        
        }
*/
        
        //LivroDAO.deletarLivro("Harry Potter");
        //LivroDAO.atualizarLivro(2, "Senhor dos Aneis", "Tolkien ", "Fantasia");
        
        
    }
}
