/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrayList;

import java.util.ArrayList;

public class App {


    public static void main(String[] args) {
        // Estamos declarando um ArrayList que aceita Strings
        ArrayList<String> nomes = new ArrayList<>();
        // Para adicionar, usamos ".add(valor)"
        nomes.add("Pedro");
        nomes.add("Diego");
        nomes.add("Leonardo"); 
        nomes.add("Diego");
        System.out.println("");
        System.out.println(nomes);
        
        // Para remover, usamos ".remove(indice)"
        nomes.remove(0);
        System.out.println(nomes);
        
        // O método .add permite adicionar o item no indice espesificado
        nomes.add(1, "Gregs");
        System.out.println(nomes);
        
        // O método .remove permite remover por valor tambem
        // Ele remove o primeiro item que tiver aquele valor
        nomes.remove("Gregs");
        System.out.println(nomes);
        
        // O método .get(indice) me permite acessar um valor dentro do ArrayList
        String elemento = nomes.get(0); // "Diego"   
        System.out.println(elemento);
        
        // O método .indiceOf(valor) retorna o indice do item que eu solicitei
        // Retorna -1 caso o ArrayList não tenha este item
        int indiceNome = nomes.indexOf("Leonardo");
        System.out.println(indiceNome);
        
        // O método .lastIndexOf(valor) retorna o indice do ultimo item com o valor que eu solicitei
        // retona -1 caso o ArrayList não tenha este item
        int ultimoIndiceNome = nomes.lastIndexOf("Diego");
        System.out.println(ultimoIndiceNome);
        
        // O método .set(indice, valor) permite trocar o valor de um item passando
        // o indice do item que queremos trocar e o novo valor
        nomes.set(2, "Arthur");
        System.out.println(nomes);
        
        // O método .size() retorna a quantidade de itens do ArrayList
        int tamanho = nomes.size();
        System.out.println(tamanho);
        
        // O método .isEmpty() retorna "true" se o ArrayList estiver vazio
        // e retorna "false" se ele tiver algum item
        System.out.println(nomes.isEmpty());
        
        // O método .contains(valor) verifica se o ArrayList tem um determinado item ou não
        boolean contem = nomes.contains("Pedro");
        System.out.println(contem);
        
        // O método clear() remove todos os itens do ArrayList
        // não retorna nada
        nomes.clear();
        System.out.println(nomes);
        
        ArrayList<Integer> numero = new ArrayList<>();
        numero.add(1);
        numero.add(20);
        numero.add(99);
        System.out.println(numero);
        //----------------------------
        numero.remove(1);
        System.out.println(numero);
        //---------------------------
        numero.add(1, 5);
        System.out.println(numero);
        //---------------------------
        System.out.println(numero.get(0));
        //---------------------------------------
        numero.set(0,3 );
        System.out.println(numero);
        //----------------------------
        System.out.println(numero.indexOf(99));
        //----------------------------------------
        numero.clear();
        System.out.println(numero);
        //----------------------------------------
        System.out.println(numero.isEmpty());
        
        
        
            
    }
}
