/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conectandoComBanco;

import java.sql.Connection;

public class App {
    

    public static void main(String[] args) {
        // Conecta com o banco
        Connection conexao = ConexaoSQLite.conectar();
        
        
        //DeletarUsuario.deletarUsuario(conexao, 1);
        //DeletarUsuario.deletarUsuario(conexao, "Arthur@gmail.com");
        CriarTabela.criarTabelaUsuarios(conexao);
    }
}
