/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conectandoComBanco;

import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PEDROHENRIQUEEICHAMA
 */
public class TelaCliente extends javax.swing.JFrame {
    // Abre a conexão
    Connection conexao = ConexaoSQLite.conectar();
    
    DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID", "Nome", "Email"}, 0
    );
    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emailFild = new javax.swing.JTextField();
        nameFild = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTable = new javax.swing.JTable();
        novoEmailFild = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));

        emailFild.setForeground(new java.awt.Color(0, 0, 0));
        emailFild.setText("Email:");
        emailFild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFildFocusLost(evt);
            }
        });

        nameFild.setForeground(new java.awt.Color(0, 0, 0));
        nameFild.setText("Nome:");
        nameFild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFildFocusLost(evt);
            }
        });

        btnAdicionar.setBackground(new java.awt.Color(0, 255, 255));
        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(0, 0, 0));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Deletar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        listaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listaTable);

        novoEmailFild.setForeground(new java.awt.Color(0, 0, 0));
        novoEmailFild.setText("NovoEmail:");
        novoEmailFild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                novoEmailFildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                novoEmailFildFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailFild)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(novoEmailFild))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(259, 259, 259)
                    .addComponent(nameFild, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(301, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(emailFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(novoEmailFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnAdicionar)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(nameFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(463, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Atualizar usuario
        String nome = nameFild.getText();
        String email = emailFild.getText();
        String novoEmail = novoEmailFild.getText();
        
        AtualizarUsuario.autualizarUsuario(conexao, email, nome, novoEmail);
        carregarTabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Deletar usuario
        String email = emailFild.getText();
        DeletarUsuario.deletarUsuario(conexao, email);
        carregarTabela();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void carregarTabela(){
        model.setRowCount(0);
        // ArrayList que recebe o retorno da função listarUsuarios
        ArrayList<Usuarios> usuarios = ListarUsuarios.listarClientes(conexao);
        
        // Este for percorre todo o nosso arrayList 'usuarios'
        // como nosso arrayList é dp tipo clientes
        // e como cado usuario tem getId, getNome e getEmail
        // pegamos estas informações e adicionamos cada cliente
        // como uma linha novo na nosso tabela
        for(Usuarios usuario : usuarios){
            model.addRow(new Object[]{
            usuario.getId(),
            usuario.getNome(),
            usuario.getEmail()
            });
        }
        listaTable.setModel(model);
    }
    
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        String nome = nameFild.getText();
        String email = emailFild.getText();
        // Adicionar o usuario
        InserirUsuario.inserUsuario(conexao, nome, email);
        carregarTabela();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void nameFildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFildFocusGained
        if("Nome:".equals(nameFild.getText())){
            nameFild.setText("");
        }
    }//GEN-LAST:event_nameFildFocusGained

    private void nameFildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFildFocusLost
        if("".equals(nameFild.getText())){
            nameFild.setText("Nome:");
        }
    }//GEN-LAST:event_nameFildFocusLost

    private void emailFildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFildFocusGained
        if("Email:".equals(emailFild.getText())){
            emailFild.setText("");
        }
        
    }//GEN-LAST:event_emailFildFocusGained

    private void emailFildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFildFocusLost
        if("".equals(emailFild.getText())){
            emailFild.setText("Email:");
        }
    }//GEN-LAST:event_emailFildFocusLost

    private void novoEmailFildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_novoEmailFildFocusGained
       if("NovoEmail:".equals(novoEmailFild.getText())){
            novoEmailFild.setText("");
        }
    }//GEN-LAST:event_novoEmailFildFocusGained

    private void novoEmailFildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_novoEmailFildFocusLost
        if("".equals(novoEmailFild.getText())){
            novoEmailFild.setText("NovoEmail:");
        }
    }//GEN-LAST:event_novoEmailFildFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JTextField emailFild;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaTable;
    private javax.swing.JTextField nameFild;
    private javax.swing.JTextField novoEmailFild;
    // End of variables declaration//GEN-END:variables
}
