/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Biblioteca;

import java.sql.Connection;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Conecta com o banco
        Connection conexao = ConexaoSQLite.conectar();
        
        
       
    }
}
