/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Biblioteca;

import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PEDROHENRIQUEEICHAMA
 */
public class TelaBiblioteca extends javax.swing.JFrame {
    
    Connection conexao = ConexaoSQLite.conectar();
    
      DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID", "Titulo", "Autor"}, 0
    );
    /**
     * Creates new form TelaBiblioteca
     */
    public TelaBiblioteca() {
        initComponents();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloFild = new javax.swing.JTextField();
        autorFild = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        livroTable = new javax.swing.JTable();
        novoTituloFild = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tituloFild.setBackground(new java.awt.Color(0, 0, 0));
        tituloFild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tituloFild.setForeground(new java.awt.Color(255, 255, 255));
        tituloFild.setText("Digite o titulo do livro:");
        tituloFild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tituloFildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tituloFildFocusLost(evt);
            }
        });
        tituloFild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloFildActionPerformed(evt);
            }
        });

        autorFild.setBackground(new java.awt.Color(0, 0, 0));
        autorFild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        autorFild.setForeground(new java.awt.Color(255, 255, 255));
        autorFild.setText("Digite o autor do livro:");
        autorFild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                autorFildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                autorFildFocusLost(evt);
            }
        });
        autorFild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorFildActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Remover");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cadastrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Listar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Biblioteca");

        livroTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(livroTable);

        novoTituloFild.setBackground(new java.awt.Color(0, 0, 0));
        novoTituloFild.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        novoTituloFild.setForeground(new java.awt.Color(255, 255, 255));
        novoTituloFild.setText("Digite o novo Titulo:");
        novoTituloFild.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                novoTituloFildFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                novoTituloFildFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(autorFild, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(tituloFild)
                            .addComponent(novoTituloFild))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(tituloFild, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autorFild, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(novoTituloFild, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloFildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloFildActionPerformed

    private void autorFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorFildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorFildActionPerformed

    private void tituloFildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tituloFildFocusGained
        if("Digite o titulo do livro:".equals(tituloFild.getText())){
            tituloFild.setText("");
        }
    }//GEN-LAST:event_tituloFildFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Cadastrar Livro
        String titulo = tituloFild.getText();
        String autor = autorFild.getText();
        
        LivroOperacaoes.cadastrarLivro(conexao, titulo, autor);
        carregarTabela();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Remover Livro
        String titulo = tituloFild.getText();
        String autor = autorFild.getText();
        
        LivroOperacaoes.removerLivro(conexao, titulo);
        carregarTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // Atualizar Livro
       String titulo = tituloFild.getText();
       String autor = autorFild.getText();
       String novoTitulo = novoTituloFild.getText();
       LivroOperacaoes.autualizarLivro(conexao, titulo, novoTitulo);
       carregarTabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String titulo = tituloFild.getText();
    carregarTabelaPorTitulo(titulo);
    }//GEN-LAST:event_jButton4ActionPerformed

     
    private void tituloFildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tituloFildFocusLost
        if("".equals(tituloFild.getText())){
            tituloFild.setText("Digite o titulo do livro:");
        }
    }//GEN-LAST:event_tituloFildFocusLost

    private void autorFildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_autorFildFocusGained
        if("Digite o autor do livro:".equals(autorFild.getText())){
            autorFild.setText("");
        }
    }//GEN-LAST:event_autorFildFocusGained

    private void autorFildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_autorFildFocusLost
        if("".equals(autorFild.getText())){
            autorFild.setText("Digite o autor do livro:");
        }
    }//GEN-LAST:event_autorFildFocusLost

    private void novoTituloFildFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_novoTituloFildFocusGained
        if("Digite o novo Titulo:".equals(novoTituloFild.getText())){
            novoTituloFild.setText("");
        }
    }//GEN-LAST:event_novoTituloFildFocusGained

    private void novoTituloFildFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_novoTituloFildFocusLost
        if("".equals(novoTituloFild.getText())){
            novoTituloFild.setText("Digite o novo Titulo:");
        }
    }//GEN-LAST:event_novoTituloFildFocusLost
    
    private void carregarTabela(){
        model.setRowCount(0);
        // ArrayList que recebe o retorno da função listarUsuarios
        ArrayList<Livros> livro = LivroOperacaoes.listarLivros(conexao);
        
        // Este for percorre todo o nosso arrayList 'usuarios'
        // como nosso arrayList é dp tipo clientes
        // e como cado usuario tem getId, getNome e getEmail
        // pegamos estas informações e adicionamos cada cliente
        // como uma linha novo na nosso tabela
        for(Livros livros : livro){
            model.addRow(new Object[]{
            livros.getId(),
            livros.getTitulo(),
            livros.getAutor()
            });
        }
        livroTable.setModel(model);
    }
    
   private void carregarTabelaPorTitulo(String titulo){
    model.setRowCount(0);

    ArrayList<Livros> livros = LivroOperacaoes.listarTitulo(conexao, titulo);

    for (Livros livro : livros) {
        model.addRow(new Object[]{
            livro.getId(),
            livro.getTitulo(),
            livro.getAutor()
        });
    }

    livroTable.setModel(model);
}
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autorFild;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable livroTable;
    private javax.swing.JTextField novoTituloFild;
    private javax.swing.JTextField tituloFild;
    // End of variables declaration//GEN-END:variables
}
