/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PrimeiroProjeto;

import java.util.Arrays;

public class App {
    

    public static void main(String[] args) {
        // Atalho: 'sou' e aí pressione ctrl + espaço + enter
        System.out.println("Hello World!");
        
        Pessoa pessoa = new Pessoa();
        pessoa.apresentar();
        
       
            
        
    }
}
 